insert into BK_LOCATION_SECTION_MAP (LOCATION_ID, SECTION_ID) values (1, 1);
insert into BK_LOCATION_SECTION_MAP (LOCATION_ID, SECTION_ID) values (2, 2);
insert into BK_LOCATION_SECTION_MAP (LOCATION_ID, SECTION_ID) values (1, 3);
insert into BK_LOCATION_SECTION_MAP (LOCATION_ID, SECTION_ID) values (2, 4);
insert into BK_LOCATION_SECTION_MAP (LOCATION_ID, SECTION_ID) values (1, 2);
insert into BK_LOCATION_SECTION_MAP (LOCATION_ID, SECTION_ID) values (2, 3);
